name: Storybook

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: storybook-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build
        run: npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: ${{ github.head_ref || github.ref_name }}
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/pr-comment
        with:
          header: ":tada: Preview available!"
          msg: |
            :tada: Preview available!
            <https://juniorboos.github.io/multiple-pr-environments/${{ github.head_ref }}>
